# **VERİ ÖNİŞLEME(DATA PREPROCESSING)**

In [ ]:
import pandas as pd

#veriyükleme

csv_veriler = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/eksikveriler.csv")

#print(csv_veriler)
print(csv_veriler[["boy", "yas", "kilo"]])



    boy   yas  kilo
0   130  10.0    30
1   125  11.0    36
2   135  10.0    34
3   133   9.0    30
4   129  12.0    38
5   180  30.0    90
6   190  25.0    80
7   175  35.0    90
8   177  22.0    60
9   185  33.0   105
10  165  27.0    55
11  155  44.0    50
12  160   NaN    58
13  162  41.0    59
14  167  55.0    62
15  174  47.0    70
16  193   NaN    90
17  187  27.0    80
18  183  28.0    88
19  159  29.0    40
20  164  32.0    66
21  166  42.0    56


# EKSİK VERİLER

In [ ]:
import numpy as np
from sklearn.impute import SimpleImputer

#eksik veriler

imputer = SimpleImputer(missing_values=np.nan, strategy="mean")

yas = csv_veriler.iloc[:,1:4].values

#eğitim öncesi eksik verili kısım
print(yas)
print("")

# eğitim kısmı -> fit ile eksik verileri öğretiyoruz
imputer.fit(yas[:,1:4])

# fit ile öğrenilen parametreleri kullanarak veri setindeki eksik
# kısımları da transform ile dolduruyoruz
yas[:,1:4] = imputer.transform(yas[:,1:4])

print(yas)
print("")


[[130.  30.  10.]
 [125.  36.  11.]
 [135.  34.  10.]
 [133.  30.   9.]
 [129.  38.  12.]
 [180.  90.  30.]
 [190.  80.  25.]
 [175.  90.  35.]
 [177.  60.  22.]
 [185. 105.  33.]
 [165.  55.  27.]
 [155.  50.  44.]
 [160.  58.  nan]
 [162.  59.  41.]
 [167.  62.  55.]
 [174.  70.  47.]
 [193.  90.  nan]
 [187.  80.  27.]
 [183.  88.  28.]
 [159.  40.  29.]
 [164.  66.  32.]
 [166.  56.  42.]]

[[130.    30.    10.  ]
 [125.    36.    11.  ]
 [135.    34.    10.  ]
 [133.    30.     9.  ]
 [129.    38.    12.  ]
 [180.    90.    30.  ]
 [190.    80.    25.  ]
 [175.    90.    35.  ]
 [177.    60.    22.  ]
 [185.   105.    33.  ]
 [165.    55.    27.  ]
 [155.    50.    44.  ]
 [160.    58.    28.45]
 [162.    59.    41.  ]
 [167.    62.    55.  ]
 [174.    70.    47.  ]
 [193.    90.    28.45]
 [187.    80.    27.  ]
 [183.    88.    28.  ]
 [159.    40.    29.  ]
 [164.    66.    32.  ]
 [166.    56.    42.  ]]



# KATEGORİK VERİLERİN SAYISAL DEĞERLERE DÖNÜŞTÜRÜLMESİ


In [ ]:
# kategorik verilerin sayısal değerlere dönüştürülmesi(categoric -> numeric)

from sklearn import preprocessing

ulkeler = csv_veriler.iloc[:, 0:1].values
print(ulkeler)
print("")

# Label Encoder kullanarak verileri sayısal değerlere dönüştürme
print("Label Encoder Kullanımı")
le = preprocessing.LabelEncoder()
ulkeler[:, 0] = le.fit_transform(ulkeler[:,0])
print(ulkeler)
print("")

# One Hot Encoder kullanarak verileri sayısal değerlere döndürme
print("One Hot Encoder Kullanımı")
ohe = preprocessing.OneHotEncoder()
ulkeler = ohe.fit_transform(ulkeler).toarray()
print(ulkeler)
print("")

[['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']]

Label Encoder Kullanımı
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]

One Hot Encoder Kullanımı
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]



# VERİLERİN BİRLEŞTİRİLMESİ VE DATAFRAME OLUŞTURULMASI


In [ ]:
# numpy dizilerinin dataframe'lere dönüştürlmesi
df_ulke = pd.DataFrame(data = ulkeler, index = range(22), columns = ["fr", "tr", "us"])
print(df_ulke)
df_boy_kilo_yas = pd.DataFrame(data = yas, index = range(22), columns = ["boy", "kilo", "yas"] )
print(df_boy_kilo_yas)
cinsiyet = csv_veriler.iloc[: , -1].values
df_cinsiyet = pd.DataFrame(data = cinsiyet, index = range(22), columns = ["cinsiyet"])
print(df_cinsiyet)

# dataframe birlşetirme işlemleri

# ülkeler ve boy kilo yaş sütunlarını içeren dataframe
df_1 = pd.concat([df_ulke, df_boy_kilo_yas], axis = 1)
print(df_1)

# ülkeler, boy, kilo, yaş sütunlarına ek cinsiyet sütununun eklendiği
# dataframe birleştirme işlemi
total_df = pd.concat([df_ulke, df_boy_kilo_yas, df_cinsiyet], axis=1)
print(total_df)

     fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0
      boy   kilo    yas
0   130.0   30.0  10.00
1   125.0   36.0  11.00
2   135.0   34.0  10.00
3   133.0   30.0   9.00
4   129.0   38.0  12.00
5   180.0   90.0  30.00
6   190.0   80.0  25.00
7   175.0   90.0  35.00
8   177.0   60.0  22.00
9   185.0  105.0  33.00
10  165.0   55.0  27.00
11  155.0   50.0  44.00
12  160.0   58.0  28.45
13  162.0   59.0  41.00
14  167.0   62.0  55.00
15  174.0   70.0  47.00
16  193.0   90.0  28.45
17  187.0   80.0  27.00
18  183.0   88.0  28.00
19  159.0   40.0  29.00
20  164.0   66.0  32.00
21  166.0   56.0  42.00
   cinsiyet
0         e
1         

# VERİ KÜMESİNİ EĞİTİM VE TEST OLARAK BÖLME

In [ ]:
from sklearn.model_selection import train_test_split

# Verilerin eğitim ve test için bölünme işlemlerinin gerçekleştirilimi

x_train, x_test, y_train, y_test = train_test_split(df_1, df_cinsiyet, test_size=0.33, random_state=0)

print(x_train)
print(x_test)


     fr   tr   us    boy   kilo    yas
8   0.0  1.0  0.0  177.0   60.0  22.00
6   0.0  1.0  0.0  190.0   80.0  25.00
16  1.0  0.0  0.0  193.0   90.0  28.45
4   0.0  1.0  0.0  129.0   38.0  12.00
2   0.0  1.0  0.0  135.0   34.0  10.00
5   0.0  1.0  0.0  180.0   90.0  30.00
17  1.0  0.0  0.0  187.0   80.0  27.00
9   0.0  0.0  1.0  185.0  105.0  33.00
7   0.0  1.0  0.0  175.0   90.0  35.00
18  1.0  0.0  0.0  183.0   88.0  28.00
3   0.0  1.0  0.0  133.0   30.0   9.00
0   0.0  1.0  0.0  130.0   30.0  10.00
15  1.0  0.0  0.0  174.0   70.0  47.00
12  0.0  0.0  1.0  160.0   58.0  28.45
     fr   tr   us    boy  kilo   yas
20  1.0  0.0  0.0  164.0  66.0  32.0
10  0.0  0.0  1.0  165.0  55.0  27.0
14  0.0  0.0  1.0  167.0  62.0  55.0
13  0.0  0.0  1.0  162.0  59.0  41.0
1   0.0  1.0  0.0  125.0  36.0  11.0
21  1.0  0.0  0.0  166.0  56.0  42.0
11  0.0  0.0  1.0  155.0  50.0  44.0
19  1.0  0.0  0.0  159.0  40.0  29.0


# ÖZNİTELİKLERİN ÖLÇEKLENDİRİLMESİ

Özniteliklerin ölçeklendirilmesi veri setindeki farklı ölçeklerde olan verilerin standart bir dağılıma dönüştürülmesini sağlayarak modelin daha hızlı ve iyi bir şekilde öğrenmesini sağlar.

In [ ]:
from sklearn.preprocessing import StandardScaler

# Verilerin ölçeklendirilme işlemleri

S_sc = StandardScaler()
X_train = S_sc.fit_transform(x_train)
X_test = S_sc.fit_transform(x_test)

print(X_train)
print("")
print(X_test)

[[-0.63245553  0.8660254  -0.40824829  0.45049444 -0.29657884 -0.24717129]
 [-0.63245553  0.8660254  -0.40824829  1.00824945  0.5096549   0.03416189]
 [ 1.58113883 -1.15470054 -0.40824829  1.13696215  0.91277178  0.35769504]
 [-0.63245553  0.8660254  -0.40824829 -1.6089087  -1.18343596 -1.18494855]
 [-0.63245553  0.8660254  -0.40824829 -1.35148331 -1.34468271 -1.372504  ]
 [-0.63245553  0.8660254  -0.40824829  0.57920713  0.91277178  0.50305051]
 [ 1.58113883 -1.15470054 -0.40824829  0.87953676  0.5096549   0.22171734]
 [-0.63245553 -1.15470054  2.44948974  0.79372829  1.51744708  0.78438369]
 [-0.63245553  0.8660254  -0.40824829  0.36468597  0.91277178  0.97193914]
 [ 1.58113883 -1.15470054 -0.40824829  0.70791983  0.8321484   0.31549506]
 [-0.63245553  0.8660254  -0.40824829 -1.43729177 -1.50592946 -1.46628173]
 [-0.63245553  0.8660254  -0.40824829 -1.56600447 -1.50592946 -1.372504  ]
 [ 1.58113883 -1.15470054 -0.40824829  0.32178174  0.10653803  2.09727185]
 [-0.63245553 -1.15470054