In [11]:
#kütüphanelerin yüklenmesi
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.tree import DecisionTreeClassifier

#verinin yüklenmesi
veriler = pd.read_csv('/content/drive/MyDrive/Colab Notebooks(ML)/CLASSIFICATION/5-DECISIONTREE/veriler.csv')

#bağımlı ve bağımsız değişkenlerin hazırlanması
x = veriler.iloc[:,1:4]
y = veriler.iloc[:,4:]
X = x.values
Y = y.values

#değişkenlerin eğitim ve test verilerine ayrıştırılması
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=0)
y_train = y_train.ravel()
y_test = y_test.ravel()

#değişkenlerin ölçeklendirilmesi
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)


#model eğitimi ve tahminlemesi(logistik regresyon)
print("Gerçek veri değeri:")
print(y_test, "\n")

log_reg = LogisticRegression(random_state=0)
log_reg.fit(X_train, y_train)

y_pred = log_reg.predict(X_test).ravel()
print("Logistik regresyon tahmini:")
print(y_pred, "\n")

#confusion matrix uygulaması
confusionMatrix = confusion_matrix(y_test, y_pred)
print("Logistik Regresyon confusion matrix:")
print(confusionMatrix, '\n')


#model eğitimi ve tahminlemesi(knn)

print("Gerçek veri değeri:")
print(y_test, "\n")

knn = KNeighborsClassifier(n_neighbors = 1, metric = 'minkowski')
knn.fit(X_train, y_train)
y_pred2 = knn.predict(X_test).ravel()
print("K-NN tahmini:")
print(y_pred2, '\n')

print("K-NN confusion matrix:")
cm = confusion_matrix(y_test, y_pred2)
print(cm, '\n')

#model eğitimi ve tahminlemesi(svc)

print("Gerçek veri değeri:")
print(y_test, "\n")

svc = SVC(kernel="rbf")
svc.fit(X_train, y_train)
y_pred3 = svc.predict(X_test).ravel()
print("SVC tahmini:")
print(y_pred3, '\n')

print("SVC confusion matrix:")
cm_svc = confusion_matrix(y_test, y_pred3)
print(cm_svc, '\n')

#model eğitimi ve tahminlemesi(naive_bayes)

print("Gerçek veri değeri:")
print(y_test, "\n")

#GAUSSIAN NAIVE BAYES
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred4 = gnb.predict(X_test).ravel()
print("GNB tahmini:")
print(y_pred4, '\n')

print("GNB confusion matrix:")
cm_gnb = confusion_matrix(y_test, y_pred4)
print(cm_gnb, '\n')


#BERNOULLI NAIVE BAYES
print("Gerçek veri değeri:")
print(y_test, "\n")

bnb = BernoulliNB()
bnb.fit(X_train, y_train)
y_pred5 = bnb.predict(X_test).ravel()
print("BNB tahmini:")
print(y_pred5, '\n')

print("BNB confusion matrix:")
cm_bnb = confusion_matrix(y_test, y_pred5)
print(cm_bnb, '\n')


#model eğitimi ve tahminlemesi(decision_tree(with gini & entropy criterions))
criterion_params = ['entropy', 'gini']
for param in criterion_params:
  dtc = DecisionTreeClassifier(criterion=param)
  dtc.fit(X_train, y_train)
  y_pred6 = dtc.predict(X_test).ravel()

  print("Gerçek veri değeri:")
  print(y_test, "\n")
  print(f"DTC({param}) tahmini:")
  print(y_pred6, '\n')

  cm_dtc = confusion_matrix(y_test, y_pred6)
  print(cm_dtc, '\n')


Gerçek veri değeri:
['k' 'k' 'k' 'k' 'e' 'k' 'k' 'k'] 

Logistik regresyon tahmini:
['e' 'e' 'e' 'e' 'k' 'e' 'e' 'e'] 

Logistik Regresyon confusion matrix:
[[0 1]
 [7 0]] 

Gerçek veri değeri:
['k' 'k' 'k' 'k' 'e' 'k' 'k' 'k'] 

K-NN tahmini:
['k' 'k' 'e' 'k' 'e' 'k' 'k' 'k'] 

K-NN confusion matrix:
[[1 0]
 [1 6]] 

Gerçek veri değeri:
['k' 'k' 'k' 'k' 'e' 'k' 'k' 'k'] 

SVC tahmini:
['e' 'k' 'e' 'e' 'e' 'e' 'e' 'k'] 

SVC confusion matrix:
[[1 0]
 [5 2]] 

Gerçek veri değeri:
['k' 'k' 'k' 'k' 'e' 'k' 'k' 'k'] 

GNB tahmini:
['e' 'e' 'e' 'e' 'k' 'e' 'e' 'k'] 

GNB confusion matrix:
[[0 1]
 [6 1]] 

Gerçek veri değeri:
['k' 'k' 'k' 'k' 'e' 'k' 'k' 'k'] 

BNB tahmini:
['k' 'k' 'e' 'k' 'k' 'k' 'k' 'k'] 

BNB confusion matrix:
[[0 1]
 [1 6]] 

Gerçek veri değeri:
['k' 'k' 'k' 'k' 'e' 'k' 'k' 'k'] 

DTC(entropy) tahmini:
['e' 'k' 'k' 'k' 'e' 'k' 'k' 'k'] 

[[1 0]
 [1 6]] 

Gerçek veri değeri:
['k' 'k' 'k' 'k' 'e' 'k' 'k' 'k'] 

DTC(gini) tahmini:
['e' 'k' 'k' 'k' 'e' 'k' 'k' 'k'] 

[[1 0]